Repository Movielity/Movielity_iOS, pull requests merged in 2024-10, with the labels that each got.

#2 Feat/#1 network api setting
  Movielity.xcodeproj/project.pbxproj
  Movielity/NetworkManager.swift
Labels: 📬 API, ⚙ Setting

#4 [FEAT/#3] SPM 설치
  Movielity.xcodeproj/project.pbxproj
Labels: ⚙ Setting

#8 [PR/#5] Network API 구현 1차
  Movielity.xcodeproj/project.pbxproj
  Movielity/Network/Base/HTTPHeaderField.swift
  Movielity/Network/Base/Router.swift
  Movielity/Network/Base/TargetType.swift
  Movielity/Network/Search/Search.swift
  Movielity/Network/Search/SearchNetworkManager.swift
  Movielity/Network/Trending/TrendingMovie.swift
  Movielity/Network/Trending/TrendingNetworkManager.swift
  Movielity/Network/Trending/TrendingSeries.swift
  Movielity/NetworkManager.swift
  Movielity/ViewController.swift
Labels: 📬 API, ✨ Feature

#9 Feat/#6 home view UI
  .gitignore
  Movielity.xcodeproj/project.pbxproj
  Movielity/APIKey.swift
  Movielity/APIUrl.swift
  Movielity/Base/BaseCollectionViewCell.swift
  Movielity/Base/BaseTableViewCell.swift
  Movielity/Base/BaseView.swift
  Movielity/Base/BaseViewController.swift
  Movielity/CustomAppColors.swift
  Movielity/HomeCollectionViewCell.swift
  Movielity/HomePosterTableViewCell.swift
  Movielity/HomeTableViewCell.swift
  Movielity/HomeView.swift
  Movielity/HomeViewController.swift
  Movielity/ReusableProtocol.swift
  Movielity/SceneDelegate.swift
  Movielity/UICollectionViewLayout +.swift
Labels: ✨ Feature

#10 [FEAT/#7] Search View UI
  Movielity.xcodeproj/project.pbxproj
  Movielity/Application/AppDelegate.swift
  Movielity/Application/SceneDelegate.swift
  Movielity/Base.lproj/Main.storyboard
  Movielity/Global/Extensions/UICollectionViewLayout +.swift
  Movielity/Global/Model/DummyMovieDTO.swift
  Movielity/Global/Protocols/ReusableProtocol.swift
  Movielity/Global/Resources/APIKey.swift
  Movielity/Global/Resources/APIUrl.swift
  Movielity/Global/Resources/Assets.xcassets/AccentColor.colorset/Contents.json
  Movielity/Global/Resources/Assets.xcassets/AppIcon.appiconset/Contents.json
  Movielity/Global/Resources/Assets.xcassets/Contents.json
  Movielity/Global/Resources/CustomAppColors.swift
  Movielity/Info.plist
  Movielity/Network/NetworkManager.swift
  Movielity/Presentation/Base/BaseCollectionViewCell.swift
  Movielity/Presentation/Base/BaseTableViewCell.swift
  Movielity/Presentation/Base/BaseView.swift
  Movielity/Presentation/Base/BaseViewController.swift
  Movielity/Presentation/Home/HomeCollectionViewCell.swift
  Movielity/Presentation/Home/HomePosterTableViewCell.swift
  Movielity/Presentation/Home/HomeTableViewCell.swift
  Movielity/Presentation/Home/HomeView.swift
  Movielity/Presentation/Home/HomeViewController.swift
  Movielity/Presentation/Search/MovieLikedTableViewCell.swift
  Movielity/Presentation/Search/SearchView.swift
  Movielity/Presentation/Search/SearchViewController.swift
  Movielity/Presentation/Search/SearchViewModel.swift
  Movielity/Presentation/SearchResults/ResultItemCollectionViewCell.swift
  Movielity/Presentation/SearchResults/SearchResultsView.swift
  Movielity/Presentation/SearchResults/SearchResultsViewController.swift
Labels: ✨ Feature

#14 [PR/#12] TMDB API 기능 구현
  Movielity.xcodeproj/project.pbxproj
  Movielity/Network/Base/Router.swift
  Movielity/Network/Credits/Credits.swift
  Movielity/Network/Credits/CreditsNetworkManager.swift
  Movielity/Network/Genre/Genre.swift
  Movielity/Network/Genre/GenreNetworkManager.swift
  Movielity/Network/Similar/SimilarMovie.swift
  Movielity/Network/Similar/SimilarNetworkManager.swift
  Movielity/Network/Similar/SimilarSeries.swift
Labels: 📬 API, ✨ Feature

#16 [PR/#11] 홈 뷰 UI 구현, 로직 기능 구현
  Movielity.xcodeproj/project.pbxproj
  Movielity/Global/Components/CustomButton.swift
  Movielity/Presentation/Home/HomeCollectionViewCell.swift
  Movielity/Presentation/Home/HomePosterTableViewCell.swift
  Movielity/Presentation/Home/HomeTableViewCell.swift
  Movielity/Presentation/Home/HomeView.swift
  Movielity/Presentation/Home/HomeViewController.swift
  Movielity/Presentation/Home/HomeViewModel.swift
Labels: ✨ Feature

#17 [PR/#13] search view network logic
  Movielity.xcodeproj/project.pbxproj
  Movielity/Application/SceneDelegate.swift
  Movielity/Global/Model/DummyMovieDTO.swift
  Movielity/Global/Protocols/ReusableProtocol.swift
  Movielity/Global/Protocols/SearchResultsDelegate.swift
  Movielity/Global/Protocols/ViewModelType.swift
  Movielity/Network/Search/Search.swift
  Movielity/Network/Trending/TrendingMovie.swift
  Movielity/Network/Trending/TrendingSeries.swift
  Movielity/Presentation/Base/BaseViewController.swift
  Movielity/Presentation/Home/HomeViewController.swift
  Movielity/Presentation/Search/MovieLikedTableViewCell.swift
  Movielity/Presentation/Search/SearchResultsViewModel.swift
  Movielity/Presentation/Search/SearchView.swift
  Movielity/Presentation/Search/SearchViewController.swift
  Movielity/Presentation/Search/SearchViewModel.swift
  Movielity/Presentation/Search/TrendingViewModel.swift
  Movielity/Presentation/SearchResults/ResultItemCollectionViewCell.swift
  Movielity/Presentation/SearchResults/SearchResultsView.swift
  Movielity/Presentation/SearchResults/SearchResultsViewController.swift
  Movielity/Presentation/TabBar/MovielityTabBarController.swift
Labels: 📬 API, ✨ Feature, ⚙ Setting

#20 [PR/#15] 상세 페이지 로직 구현
  Movielity.xcodeproj/project.pbxproj
  Movielity/Presentation/Detail/DetailView.swift
  Movielity/Presentation/Detail/DetailViewController.swift
  Movielity/Presentation/Detail/DetailViewModel.swift
  Movielity/Presentation/Search/SearchViewController.swift
Labels: 📬 API, ✨ Feature

#19 [PR/#18] Home 뷰 TagLabel 장르 API 연결 구현
  Movielity/Network/Genre/GenreNetworkManager.swift
  Movielity/Presentation/Home/HomeView.swift
  Movielity/Presentation/Home/HomeViewController.swift
  Movielity/Presentation/Home/HomeViewModel.swift
Labels: ✨ Feature

#25 Feat/#21 alert view UI
  Movielity.xcodeproj/project.pbxproj
  Movielity/Global/Components/MovielityAlertView.swift
  Movielity/Presentation/Detail/DetailViewController.swift
  Movielity/Presentation/Detail/DetailViewModel.swift
Labels: ✨ Feature

#26 [PR/#22] UI 수정 및 데이터 전달 및 디테일뷰로 화면 전환 기능 구현
  Movielity.xcodeproj/project.pbxproj
  Movielity/Application/AppDelegate.swift
  Movielity/Global/Components/CustomButton.swift
  Movielity/Global/Resources/Assets.xcassets/Logo.imageset/Contents.json
  Movielity/Global/Resources/Assets.xcassets/Logo.imageset/single-small.png
  Movielity/Global/Resources/Assets.xcassets/Logo.imageset/single-small@2x.png
  Movielity/Global/Resources/Assets.xcassets/Logo.imageset/single-small@3x.png
  Movielity/Global/Resources/StringLiterals.swift
  Movielity/Network/Trending/TrendingSeries.swift
  Movielity/Presentation/Base/BaseView.swift
  Movielity/Presentation/Home/HomeView.swift
  Movielity/Presentation/Home/HomeViewController.swift
  Movielity/Presentation/Home/HomeViewModel.swift
  Movielity/Presentation/Search/SearchTableViewCell.swift
  Movielity/Presentation/Search/SearchView.swift
  Movielity/Presentation/Search/SearchViewController.swift
  Movielity/Presentation/TabBar/MovielityTabBarController.swift
Labels: ✨ Feature, 🔨 Refactor

#28 Feat/#27 refactor issue clear
  Movielity.xcodeproj/project.pbxproj
  Movielity/Global/Extensions/UIView+.swift
  Movielity/Global/Protocols/ReusableProtocol.swift
Labels: 🔨 Refactor
